from pydantic import BaseModel
from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey, Table
from sqlalchemy.orm import relationship
from datetime import datetime
from database import Base

# Association table for Scene <-> Character (many-to-many)
# Must be defined before the classes that reference it
scene_characters = Table(
    'scene_characters',
    Base.metadata,
    Column('scene_id', Integer, ForeignKey('scenes.id'), primary_key=True),
    Column('character_id', Integer, ForeignKey('characters.id'), primary_key=True)
)

# --- SQLAlchemy Models ---
class ProjectDB(Base):
    __tablename__ = "projects"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String, nullable=False)
    genre = Column(String)
    pitch = Column(Text)
    visual_style = Column(Text)
    target_audience = Column(String)
    language = Column(String, default="French")
    target_duration = Column(String, default="60s")
    aspect_ratio = Column(String, default="16:9")
    created_at = Column(DateTime, default=datetime.utcnow)
    status = Column(String, default="concept")
    user_id = Column(String, index=True, nullable=True) # ID from Supabase Auth
    
    scenes = relationship("SceneDB", back_populates="project", cascade="all, delete-orphan", order_by="SceneDB.sequence_order")
    chat_history = relationship("ChatMessageDB", back_populates="project", cascade="all, delete-orphan")
    characters = relationship("CharacterDB", back_populates="project", cascade="all, delete-orphan")
    locations = relationship("LocationDB", back_populates="project", cascade="all, delete-orphan")

class SceneDB(Base):
    __tablename__ = "scenes"

    id = Column(Integer, primary_key=True, index=True)
    project_id = Column(Integer, ForeignKey("projects.id"))
    sequence_order = Column(Integer, nullable=False)
    title = Column(String, nullable=False)
    summary = Column(Text, nullable=False)
    script = Column(Text, nullable=True) # Generated by Scriptwriter Agent
    estimated_duration = Column(String)
    master_image_url = Column(String, nullable=True) # URL of the 3x3 grid
    status = Column(String, default="pending")
    location_id = Column(Integer, ForeignKey("locations.id"), nullable=True)

    project = relationship("ProjectDB", back_populates="scenes")
    shots = relationship("ShotDB", back_populates="scene", cascade="all, delete-orphan")
    location = relationship("LocationDB")
    characters = relationship("CharacterDB", secondary=scene_characters)

class ShotDB(Base):
    __tablename__ = "shots"

    id = Column(Integer, primary_key=True, index=True)
    scene_id = Column(Integer, ForeignKey("scenes.id"))
    shot_number = Column(Integer, nullable=False)
    visual_prompt = Column(Text, nullable=False)
    image_url = Column(String, nullable=True)
    status = Column(String, default="generating")

    scene = relationship("SceneDB", back_populates="shots")

# --- Asset Models ---
class CharacterDB(Base):
    __tablename__ = "characters"

    id = Column(Integer, primary_key=True, index=True)
    project_id = Column(Integer, ForeignKey("projects.id"))
    name = Column(String, nullable=False)
    image_url = Column(String, nullable=True)

    project = relationship("ProjectDB", back_populates="characters")

class LocationDB(Base):
    __tablename__ = "locations"

    id = Column(Integer, primary_key=True, index=True)
    project_id = Column(Integer, ForeignKey("projects.id"))
    name = Column(String, nullable=False)
    image_url = Column(String, nullable=True)

    project = relationship("ProjectDB", back_populates="locations")

# SceneCharacterDB class removed - using Table() association instead

class ChatMessageDB(Base):
    __tablename__ = "chat_messages"

    id = Column(Integer, primary_key=True, index=True)
    project_id = Column(Integer, ForeignKey("projects.id"))
    role = Column(String, nullable=False)  # 'user' or 'model'
    content = Column(Text, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)

    project = relationship("ProjectDB", back_populates="chat_history")

# --- Pydantic Schemas ---
class ChatMessageInput(BaseModel):
    content: str
    # Later we will add projectId, sceneId, etc.

class ChatMessageOutput(BaseModel):
    id: str
    role: str # "agent"
    content: str
    timestamp: str
    action_taken: bool = False

class ExtractConceptInput(BaseModel):
    messages: list[dict] # Simplified dict list, or reuse strict schema if valid


class ProjectBase(BaseModel):
    title: str
    genre: str | None = None
    pitch: str | None = None
    visual_style: str | None = None
    target_audience: str | None = None
    language: str = "French"
    target_duration: str = "60s"
    aspect_ratio: str = "16:9"
    status: str = "concept"

# --- Asset Pydantic Schemas ---
class CharacterBase(BaseModel):
    name: str
    image_url: str | None = None

class Character(CharacterBase):
    id: int
    project_id: int

    class Config:
        from_attributes = True

class LocationBase(BaseModel):
    name: str
    image_url: str | None = None

class Location(LocationBase):
    id: int
    project_id: int

    class Config:
        from_attributes = True

class SceneBase(BaseModel):
    title: str
    summary: str
    script: str | None = None
    estimated_duration: str | None = None
    master_image_url: str | None = None
    sequence_order: int | None = None
    location_id: int | None = None

class SceneCreate(SceneBase):
    pass

class Scene(SceneBase):
    id: int
    project_id: int
    status: str
    shots: list["Shot"] = []
    location: Location | None = None
    characters: list[Character] = []

    class Config:
        from_attributes = True

class ShotBase(BaseModel):
    shot_number: int
    visual_prompt: str
    image_url: str | None = None
    status: str = "generating"

class Shot(ShotBase):
    id: int
    scene_id: int

    class Config:
        from_attributes = True

class ProjectCreate(ProjectBase):
    pass

class Project(ProjectBase):
    id: int
    created_at: datetime
    scenes: list[Scene] = []
    characters: list[Character] = []
    locations: list[Location] = []

    class Config:
        from_attributes = True

