from pydantic import BaseModel
from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey
from sqlalchemy.orm import relationship
from datetime import datetime
from database import Base

# --- SQLAlchemy Models ---
class ProjectDB(Base):
    __tablename__ = "projects"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String, nullable=False)
    genre = Column(String)
    pitch = Column(Text)
    visual_style = Column(Text)
    target_audience = Column(String)
    created_at = Column(DateTime, default=datetime.utcnow)
    status = Column(String, default="concept")
    
    scenes = relationship("SceneDB", back_populates="project", cascade="all, delete-orphan")

class SceneDB(Base):
    __tablename__ = "scenes"

    id = Column(Integer, primary_key=True, index=True)
    project_id = Column(Integer, ForeignKey("projects.id"))
    sequence_order = Column(Integer, nullable=False)
    title = Column(String, nullable=False)
    summary = Column(Text, nullable=False)
    script = Column(Text, nullable=True) # Generated by Scriptwriter Agent
    estimated_duration = Column(String)
    status = Column(String, default="pending")

    project = relationship("ProjectDB", back_populates="scenes")

# --- Pydantic Schemas ---
class ChatMessageInput(BaseModel):
    content: str
    # Later we will add projectId, sceneId, etc.

class ChatMessageOutput(BaseModel):
    id: str
    role: str # "agent"
    content: str
    timestamp: str

class ProjectBase(BaseModel):
    title: str
    genre: str | None = None
    pitch: str | None = None
    visual_style: str | None = None
    target_audience: str | None = None
    status: str = "concept"

class SceneBase(BaseModel):
    title: str
    summary: str
    script: str | None = None
    estimated_duration: str | None = None
    sequence_order: int | None = None

class SceneCreate(SceneBase):
    pass

class Scene(SceneBase):
    id: int
    project_id: int
    status: str

    class Config:
        from_attributes = True

class ProjectCreate(ProjectBase):
    pass

class Project(ProjectBase):
    id: int
    created_at: datetime
    scenes: list[Scene] = []

    class Config:
        from_attributes = True
